apiVersion: apps/v1
kind: Deployment
metadata:
  name: spawnerservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spawnerservice-deployment
  template:
    metadata:
      labels:
        name: spawnerservice-deployment
    spec:
      containers:
      - name: application
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        command: [ "/go/bin/spawnersvc"]
        args: []
        env:
        - name: ENV
          value: {{ .Values.env }}
        - name: GRPC_PORT
          value: '{{ .Values.grpc_port }}'
        - name: HTTP_PORT
          value: '{{ .Values.http_port }}'
        - name: RANCHER_ADDRESS
          value: {{ .Values.rancher.address }}
        - name: RANCHER_USERNAME
          value: {{ .Values.rancher.username }}
        - name: RANCHER_PASSWORD
          value: {{ .Values.rancher.password }}
        - name: RANCHER_AWS_CRED_NAME
          value: {{ .Values.rancher.aws_cred_name }}
        - name: SECRET_HOST_REGION
          value: {{ .Values.secret_host_region }}
        - name: AWS_ROUTE53_HOSTEDZONEID
          value: {{ .Values.route53_hostedzone_id }}
        - name: NODE_DELETION_TIME_IN_SECONDS
          value: '{{ .Values.node_deletion_timeout_in_seconds }}'
        - name: AZURE_CLOUD_PROVIDER
          value: {{ .Values.azure_cloud_provider }}
        - name: OPENID_ROLE
          value: {{ .Values.openid_role }}

        ports:
          - containerPort: {{ .Values.grpc_port }} 
        securityContext:
          runAsUser: 1001
      imagePullSecrets:
        - name: dockerconfigjson-gitlab
      serviceAccountName: awskube2iam
